// Configuration for GitHub PR Dashboard
// This file can be customized to point to different data sources

const CONFIG = {
    // Data source configuration
    dataSource: {
        // Path to the JSON data files (relative to index.html)
        // These files are generated by GitHub Actions
        basePath: './data/',
        
        // Available data files
        files: {
            config: 'config.json',           // Repository configuration
            prs: 'prs.json',                // PR data for all repositories
            analytics: 'analytics.json',    // Pre-computed analytics
            cache_info: 'cache_info.json'   // Cache metadata
        }
    },
    
    // UI configuration
    ui: {
        defaultPage: 'home',
        defaultDays: 90,
        defaultStates: ['OPEN', 'MERGED'],
        theme: 'light'
    },
    
    // Chart configuration
    charts: {
        colors: {
            OPEN: '#ff4b4b',
            MERGED: '#21c354',
            CLOSED: '#6b7280',
            draft: '#ffa421'
        },
        defaultHeight: 400
    },
    
    // Repository configuration
    // These can be overridden by data/config.json
    repositories: [
        {
            name: "Streamlit",
            owner: "streamlit",
            repo: "streamlit"
        }
    ],
    
    // Primary repository index (default: 0)
    primaryRepoIndex: 0,
    
    // Date formatting
    dateFormat: {
        display: 'YYYY-MM-DD HH:mm',
        chart: 'YYYY-MM-DD'
    }
};

// Export for use in other modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = CONFIG;
}
